# Generated by Django 5.1.4 on 2024-12-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='action',
            field=models.CharField(default='get', max_length=100),
            preserve_default=False,
        ),
    ]
